jwt:
  secret: MY-Secret-Key
sample:
  value: modified value to test
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE : http://localhost:8761/eureka/}
zuul:
  routes:
    studentservice:
      path: /student-api/**
      serviceId: STUDENTSERVICE
    addressservice:
      path: /address-api/**
      serviceId: ADDRESSSERVICE
    ignored-headers: 
      - Access-Control-Allow-Credentials
      - Access-Control-Allow-Origin
    sensitive-headers:
      - Cookie
      - Set-Cookie
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
spring:
  data:
    mongodb:
      uri: mongodb://mongouser:mongopass@mycluster076-shard-00-00-duylq.mongodb.net:27017,mycluster076-shard-00-01-duylq.mongodb.net:27017,mycluster076-shard-00-02-duylq.mongodb.net:27017/test?ssl=true&replicaSet=MyCluster076-shard-0&authSource=admin&retryWrites=true&w=majority
      database: eshopping
